# same pre-req steps as mentioned in cross-osxamd64-toolchain.cmake (doing once is enough)
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_C_COMPILER aarch64-apple-darwin22-clang)
set(CMAKE_CXX_COMPILER aarch64-apple-darwin22-clang++)
set(CMAKE_ARCHITECTURE arm64)
set(CMAKE_FIND_ROOT_PATH /sdk)
set(CMAKE_OSX_SYSROOT /MacOSX13.1.sdk)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# usually <build-linux64>/tools/build/Debug/bin/nrc
set(NATIVE_NRC_PATH "" CACHE STRING "NRC path executable on host machine")
